name: Lint

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Install shadow
      env:
        GO111MODULE: off
      run: go get golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
    - name: go vet
      run: make vet
    - name: go vet shadow
      run: make vet-shadow
  gosec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: -confidence=medium -severity=medium ./...
